/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0k9wzlkLWna
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'
import { Gabarito } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"

export function Lending() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <CoinsIcon className="h-8 w-8" />
          <span className="text-xl font-bold">CryptoLends</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Lend
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Borrow
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="secondary">Connect Wallet</Button>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-16 px-6 md:px-12 flex flex-col items-center justify-center gap-8">
          <div className="max-w-3xl space-y-6 text-center">
            <h1 className="text-4xl font-bold">Lend Your Crypto</h1>
            <p className="text-muted-foreground">
              Earn passive income by lending your crypto assets to borrowers on our platform.
            </p>
            <div className="bg-white p-8 rounded-lg shadow-lg">
              <h3 className="text-2xl font-bold text-center mb-6">Earn Passive Income</h3>
              <form className="grid gap-6">
                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="asset" className="text-sm font-medium">
                      Asset
                    </Label>
                    <Select id="asset" className="w-full">
                      <SelectTrigger>
                        <SelectValue placeholder="Select an asset" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="btc">Bitcoin (BTC)</SelectItem>
                        <SelectItem value="eth">Ethereum (ETH)</SelectItem>
                        <SelectItem value="usdc">USD Coin (USDC)</SelectItem>
                        <SelectItem value="dai">DAI</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="amount" className="text-sm font-medium">
                      Amount
                    </Label>
                    <Input
                      id="amount"
                      type="number"
                      placeholder="Enter amount"
                      className="bg-gray-100 focus:bg-white"
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="term" className="text-sm font-medium">
                      Term
                    </Label>
                    <Select id="term" className="w-full">
                      <SelectTrigger>
                        <SelectValue placeholder="Select a term" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1">1 month</SelectItem>
                        <SelectItem value="3">3 months</SelectItem>
                        <SelectItem value="6">6 months</SelectItem>
                        <SelectItem value="12">12 months</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="flex items-end">
                    <Button type="submit" className="w-full bg-gray-800 hover:bg-gray-700 text-white font-medium">
                      Lend
                    </Button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </section>
        <section className="bg-background py-16 px-6 md:px-12 flex flex-col items-center justify-center gap-8">
          <div className="max-w-3xl space-y-6 text-center">
            <h2 className="text-3xl font-bold">Why Lend with CryptoLends?</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-muted p-6 rounded-xl shadow-sm">
                <PercentIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Competitive Rates</h3>
                <p className="text-muted-foreground">
                  Earn up to 8% APY on your crypto assets with our industry-leading lending rates.
                </p>
              </div>
              <div className="bg-muted p-6 rounded-xl shadow-sm">
                <LockIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Secure Lending</h3>
                <p className="text-muted-foreground">
                  Your assets are secured by our robust smart contract system and audited platform.
                </p>
              </div>
              <div className="bg-muted p-6 rounded-xl shadow-sm">
                <ClockIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Flexible Terms</h3>
                <p className="text-muted-foreground">
                  Choose from a variety of lending terms, from 1 month to 12 months, to fit your needs.
                </p>
              </div>
              <div className="bg-muted p-6 rounded-xl shadow-sm">
                <WalletIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Easy Withdrawals</h3>
                <p className="text-muted-foreground">
                  Withdraw your funds at any time with no penalties or hidden fees.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-16 px-6 md:px-12 flex flex-col items-center justify-center gap-8">
          <div className="max-w-3xl space-y-6 text-center">
            <h2 className="text-3xl font-bold">How it Works</h2>
            <div className="grid md:grid-cols-3 gap-8">
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <WalletIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Connect Wallet</h3>
                <p className="text-muted-foreground">Connect your crypto wallet to our platform to start lending.</p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <PercentIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Choose Lending Terms</h3>
                <p className="text-muted-foreground">Select the asset, amount, and term that best suits your needs.</p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <ReceiptIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Earn Passive Income</h3>
                <p className="text-muted-foreground">Sit back and watch your crypto assets earn interest over time.</p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-background py-16 px-6 md:px-12 flex flex-col items-center justify-center gap-8">
          <div className="max-w-3xl space-y-6 text-center">
            <h2 className="text-3xl font-bold">Frequently Asked Questions</h2>
            <div className="grid gap-4">
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between w-full bg-muted p-4 rounded-xl">
                  <h3 className="text-lg font-bold">What is the minimum amount I can lend?</h3>
                  <ChevronDownIcon className="h-6 w-6 text-muted-foreground" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-background p-4 rounded-xl">
                  <p className="text-muted-foreground">
                    The minimum amount you can lend is $100 or the equivalent in your chosen crypto asset.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between w-full bg-muted p-4 rounded-xl">
                  <h3 className="text-lg font-bold">How do I withdraw my funds?</h3>
                  <ChevronDownIcon className="h-6 w-6 text-muted-foreground" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-background p-4 rounded-xl">
                  <p className="text-muted-foreground">
                    You can withdraw your funds at any time by logging into your account and initiating a withdrawal.
                    There are no penalties or hidden fees for withdrawals.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between w-full bg-muted p-4 rounded-xl">
                  <h3 className="text-lg font-bold">Is my crypto secure with CryptoLends?</h3>
                  <ChevronDownIcon className="h-6 w-6 text-muted-foreground" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-background p-4 rounded-xl">
                  <p className="text-muted-foreground">
                    Yes, your crypto assets are secured by our robust smart contract system and regularly audited
                    platform. We take security very seriously to protect your funds.
                  </p>
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6 md:px-12 flex flex-col md:flex-row items-center justify-between">
        <div className="flex items-center gap-2">
          <CoinsIcon className="h-6 w-6" />
          <span>&copy; 2024 CryptoLends. All rights reserved.</span>
        </div>
        <nav className="flex items-center gap-4 mt-4 md:mt-0">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Contact Us
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function CoinsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="8" r="6" />
      <path d="M18.09 10.37A6 6 0 1 1 10.34 18" />
      <path d="M7 6h1v4" />
      <path d="m16.71 13.88.7.71-2.82 2.82" />
    </svg>
  )
}


function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function PercentIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="19" x2="5" y1="5" y2="19" />
      <circle cx="6.5" cy="6.5" r="2.5" />
      <circle cx="17.5" cy="17.5" r="2.5" />
    </svg>
  )
}


function ReceiptIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
      <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8" />
      <path d="M12 17.5v-11" />
    </svg>
  )
}


function WalletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  )
}
