/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pgomoE8mWZ7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'
import { Gabarito } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function About() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <CoinsIcon className="h-8 w-8" />
          <span className="text-xl font-bold">CryptoLends</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Lend
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Borrow
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="secondary">Connect Wallet</Button>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-16 px-6 md:px-12 flex flex-col items-center justify-center gap-8">
          <div className="max-w-3xl space-y-6 text-center">
            <h1 className="text-4xl font-bold">About CryptoLends</h1>
            <p className="text-muted-foreground">
              CryptoLends is a leading decentralized finance (DeFi) lending platform that connects lenders and borrowers
              in a secure and transparent environment. Our mission is to revolutionize the traditional lending industry
              by providing a more accessible, efficient, and equitable financial system.
            </p>
            <div className="flex gap-4 justify-center">
              <Button>Learn More</Button>
              <Button variant="secondary">Contact Us</Button>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-5xl">
            <div className="bg-background p-6 rounded-xl shadow-sm">
              <CurrencyIcon className="h-12 w-12 text-primary" />
              <h3 className="text-xl font-bold mt-4">Low Interest Rates</h3>
              <p className="text-muted-foreground mt-2">
                Enjoy competitive interest rates on your loans, with transparent and fair pricing.
              </p>
            </div>
            <div className="bg-background p-6 rounded-xl shadow-sm">
              <CheckIcon className="h-12 w-12 text-primary" />
              <h3 className="text-xl font-bold mt-4">Fast Approvals</h3>
              <p className="text-muted-foreground mt-2">
                Get your loan approved quickly, with a streamlined application process.
              </p>
            </div>
            <div className="bg-background p-6 rounded-xl shadow-sm">
              <LockIcon className="h-12 w-12 text-primary" />
              <h3 className="text-xl font-bold mt-4">Secure Transactions</h3>
              <p className="text-muted-foreground mt-2">
                Rest assured that your transactions are secure and protected, thanks to our robust security measures.
              </p>
            </div>
          </div>
        </section>
        <section className="py-16 px-6 md:px-12 bg-primary text-primary-foreground">
          <div className="max-w-5xl mx-auto space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold">Our Team</h2>
              <p className="text-primary-foreground/80">Meet the talented individuals behind CryptoLends.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="bg-background p-6 rounded-xl shadow-sm text-center">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Team Member 1" />
                  <AvatarFallback>TM1</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold mt-4">John Doe</h3>
                <p className="text-muted-foreground mt-2">Co-Founder</p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm text-center">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Team Member 2" />
                  <AvatarFallback>TM2</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold mt-4">Jane Smith</h3>
                <p className="text-muted-foreground mt-2">Chief Technology Officer</p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm text-center">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Team Member 3" />
                  <AvatarFallback>TM3</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold mt-4">Michael Johnson</h3>
                <p className="text-muted-foreground mt-2">Head of Operations</p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 px-6 md:px-12 bg-muted">
          <div className="max-w-5xl mx-auto space-y-12">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold">Our Values</h2>
              <p className="text-muted-foreground">At the core of CryptoLends are these guiding principles.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <InfoIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold mt-4">Transparency</h3>
                <p className="text-muted-foreground mt-2">
                  We believe in open and honest communication, providing clear information about our platform and
                  processes.
                </p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <AccessibilityIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold mt-4">Accessibility</h3>
                <p className="text-muted-foreground mt-2">
                  Our goal is to make DeFi lending accessible to everyone, regardless of their financial background or
                  location.
                </p>
              </div>
              <div className="bg-background p-6 rounded-xl shadow-sm">
                <InfoIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold mt-4">Innovation</h3>
                <p className="text-muted-foreground mt-2">
                  We are constantly exploring new technologies and strategies to improve the lending experience for our
                  users.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6 md:px-12 flex flex-col md:flex-row items-center justify-between">
        <div className="flex items-center gap-2">
          <CoinsIcon className="h-6 w-6" />
          <span>&copy; 2024 CryptoLends. All rights reserved.</span>
        </div>
        <nav className="flex items-center gap-4 mt-4 md:mt-0">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Contact Us
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function AccessibilityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  )
}


function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function CoinsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="8" r="6" />
      <path d="M18.09 10.37A6 6 0 1 1 10.34 18" />
      <path d="M7 6h1v4" />
      <path d="m16.71 13.88.7.71-2.82 2.82" />
    </svg>
  )
}


function CurrencyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="8" />
      <line x1="3" x2="6" y1="3" y2="6" />
      <line x1="21" x2="18" y1="3" y2="6" />
      <line x1="3" x2="6" y1="21" y2="18" />
      <line x1="21" x2="18" y1="21" y2="18" />
    </svg>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}
